### ISSUE TITLE
Minifying 1.5.8. not working for WP 1.6.2

### ISSUE THREAD

**Issue by PPAAUULL** [malihu/page-scroll-to-id#16]
The jquery.malihu.PageScroll2id.js differs from the current minified version included in wordpress (1.5.6 vs 1.6.2). 
Would be really nice if you could update the unminified js!

**Comment by malihu** [comment]
Yes this is correct. 

The WordPress plugin 1.6.2 includes page-scroll-to-id 1.5.6. 

The latest page-scroll-to-id version (1.5.8) is already included in the [WordPress plugin development version](https://downloads.wordpress.org/plugin/page-scroll-to-id.zip) which will be released as version 1.6.3. 

If you want to use page-scroll-to-id 1.5.8 in WordPress before version 1.6.3 is released, you can download and use the [development version](https://downloads.wordpress.org/plugin/page-scroll-to-id.zip).

**Comment by PPAAUULL** [comment]
Thank You – unfortunately it does not solve my issue. I wanted to modify the jquery.malihu.PageScroll2id.js and use it instead of the minified js. But that's not working. 
1. Does the minified js contain more than the jquery.malihu.PageScroll2id.js?
2. How do you minify?

**Comment by malihu** [comment]
Yes, the minified version of the WordPress plugin (`page-scroll-to-id.min.js`) contains the following: 
`jquery.malihu.PageScroll2id.js`
`jquery.malihu.PageScroll2id-init.js`

Both of these unminified files are contained in plugin's `js` directory.

In WordPress, you can instruct the plugin to load the non-minified/development version of its scripts (i.e. the 2 files above) instead of the minified/production-ready one, by adding: 

`define('PS2ID_MINIFIED_JS', false);`

to your wp-config.php

**Comment by PPAAUULL** [comment]
Thank You!
